version: "3"
services:
  webservice:
    # replace username/repo:tag with your name and image details
    image: pixelbits/console
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "0.4"
          memory: 300M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  webapp:
    # replace username/repo:tag with your name and image details
    image: pixelbits/web
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "4000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: