FROM microsoft/dotnet

COPY . /Todo

WORKDIR /Todo/TestConsole

RUN dotnet restore && dotnet publish -c Release

WORKDIR /Todo/TestConsole/bin/Release/netcoreapp2.0/publish

CMD ["dotnet", "TestConsole.dll"]